# RHEL 8.x and Centos Strem 8 are the same, keep this around for now!

- name: 'Facts are the same as in Fedora'
  include_tasks: 'Fedora.yml'

- name: Set distribution specific facts
  set_fact:
    passkey_support: No
